### ISSUE TITLE
Output as JSON-LD

### ISSUE THREAD

**Issue by janober** [Janpot/microdata-node#1]
Hello,

came across this project. First thanks for sharing. Is very helpful!

But was wondering about JSON-LD. When I use the "toJsonLd" the output is differently than I expected. Meaning if I compare the output with an example here: http://schema.org/Product
they are quite different. For example uses the full path over just the name ("http://schema.org/name" vs "name") saves the value as @value under the type instead of the normal property name as a sibling, ... and so on.

I am totally new to all of that so I am wondering. Because would have expected that identical data in the same "format" should be identical.

Thanks for your help!

**Comment by KevinMartin** [comment]
In case anyone comes to this issue later, I was able to install the `jsonld` module and compact the output like so:

```js
const microdata = require('microdata-node');
const jsonld = require('jsonld');

const html = '...';
const data = microdata.toJsonld(html);

jsonld.frame(data, { '@type': data[0]['@type'] }, callback);
```
