### ISSUE TITLE
No results from blog.schema.org

### ISSUE THREAD

**Issue by mvolz** [Janpot/microdata-node#2]
i.e. http://blog.schema.org/2014/12/schemaorg-v192-music-video-games-sports.html

I thought I was using the library wrong (still possible) until I tried a different website- a cursory glance shows there are itemprop attributes in the page so theoretically there should be extractable microdata there.

**Comment by Janpot** [comment]
This microdata is not according the spec

http://www.w3.org/TR/microdata-rdf/#dfn-top-level-item
> top-level item
> An item which does not contain an itemprop attribute. Available through the Microdata DOM API as document.getItems. (See top-level microdata item in [MICRODATA]).

http://www.w3.org/TR/microdata-rdf/#h3_rdf-conversion-algorithm
>For each element that is also a top-level item, Generate the triples for that item using the evaluation context.

The parsing algorithm states that parsing should start at top level items, all items in your page have `itemprop` attributes so they are not top-level, hence not parsed

**Comment by mvolz** [comment]
I figured! A bit ironic considering it's a schema.org website.

Any sense how common off-spec microdata is? Any chance of this library parsing it anyway? Not sure the best way to do that... just dump it all in an unstructured way somewhere?

**Comment by Janpot** [comment]
hi @mvolz ,

Two other implementations show the same behaviour http://www.w3.org/2012/pyMicrodata/ and http://rdf.greggkellogg.net/distiller. Google structure data tool does find microdata on the page, though it also reports the errors. I prefer to not deviate from the spec for now, especially when other libraries implement this spec correctly as well.

I might add a `strict` options some day and report errors and warnings, but don't expect that too soon. I checked your metadata project, I've built a similar tool for my company, I'll keep an eye on this one.

For now if you really want to extract the data out of this page, my best advice is:
either parse the html with cheerio and remove the `itemprop` attributes on all `itemscope` elements that are not nested in another `itemscope` element. Then parse the file with `microformat-node`.
or add an `itemscope` to the `<html>`, this turns the two items in the page into two properties on an anonymous object. Then parse the file with `microdata-node`.

**Comment by Janpot** [comment]
@mvolz 
version 0.2.0 now has a forgiving mode that detects this badly formatted top level items. It is on by default and can be triggered with the `strict` option.
At the same time, the `.parse` method is deprecated and replaced by the `.toJson` and `.toJsonld` methods that don't rely on cheerio and just accept the raw html.
