### ISSUE TITLE
Unable to parse nested element.

### ISSUE THREAD

**Issue by rdonmez** [Janpot/microdata-node#3]
everything is ok but unable to parsing when contains nested micro element.

i.e. http://www.ebay.com/itm/Apple-iPod-Touch-4th-Generation-MP3-Player-8GB-Black-MC540LL-A-4-Gen-/141515157926?_trksid=p2053446.m2308.l4001

FYI.

**Comment by Janpot** [comment]
@rdonmez Can you give a bit more detail on what you see and what you expect

**Comment by rdonmez** [comment]
some properties returns an empty string  when i extract micro-data from this url ( http://www.ebay.com/itm/Apple-iPod-Touch-4th-Generation-MP3-Player-8GB-Black-MC540LL-A-4-Gen-/141515157926?_trksid=p2053446.m2308.l4001) 

this properties is nested element (or item). 

please take a look to richsnippet test tool: http://www.google.com/webmasters/tools/richsnippets?q=http%3A%2F%2Fwww.ebay.com%2Fitm%2FApple-iPod-Touch-4th-Generation-MP3-Player-8GB-Black-MC540LL-A-4-Gen-%2F141515157926%3F_trksid%3Dp2053446.m2308.l4001

thanks. 

here is my result;
{
  "items": [
    {
      "type": [
        "http://schema.org/Product"
      ],
      "properties": {
        "image": [
          "http://i.ebayimg.com/00/$(KGrHqZ,!iwE6HRE+C,bBOpsT)y8Iw~~_35.JPG?set_id=89040003C1",
          "http://i.ebayimg.com/00/$(KGrHqZ,!iwE6HRE+C,bBOpsT)y8Iw~~_35.JPG?set_id=89040003C1"
        ],
        "name": [
          "Details about   Apple iPod Touch 4th Generation MP3 Player - 8GB, Black MC540LL/A 4 Gen"
        ],
        "aggregateRating": [
          {
            "type": [
              "http://schema.org/AggregateRating"
            ],
            "properties": {
              "ratingValue": [
                ""
              ],
              "reviewCount": [
                ""
              ]
            }
          }
        ],
        "offers": [
          {
            "type": [
              "http://schema.org/Offer"
            ],
            "properties": {
              "price": [
                "US $74.95"
              ],
              "availability": [
                ""
              ],
              "priceCurrency": [
                ""
              ]
            }
          }
        ],
        "brand": [
          {
            "type": [
              "http://schema.org/Brand"
            ],
            "properties": {
              "name": [
                "Apple"
              ]
            }
          }
        ],
        "model": [
          "iPod Touch 4th Generation"
        ],
        "color": [
          "Black"
        ],
        "mpn": [
          "MC540LL/A"
        ],
        "gtin13": [
          "885909394845"
        ]
      }
    }
  ]
}

**Comment by Janpot** [comment]
@rdonmez This is what I find in the source
```
<span itemprop="ratingValue" content="4.5" ></span>
<span itemprop="reviewCount" content="3018" ></span>
```
neither the HTML5 spec nor the Microdata spec specify a `content` attribute for a `span` element. To make this valid Microdata this should be turned into a `meta` tag.

https://html.spec.whatwg.org/multipage/microdata.html#values

Both of following microdata parser implementations show the same behaviour:
http://rdf.greggkellogg.net/distiller
http://www.w3.org/2012/pyMicrodata/

I might add some relaxing options someday to ignore errors and warnings.

**Comment by rdonmez** [comment]
thanks to reply.

**Comment by Janpot** [comment]
@rdonmez 
I just added a forgiving mode which is the default in v0.2.1 which should detect these properties.
In this version the `.parse` method is deprecated in favor for the `.toJson` and `.toJsonld` methods which just accept raw html input instead of the cheerio object.
