### ISSUE TITLE
when property contains paragraph elements, words unintentionally collide

### ISSUE THREAD

**Issue by AMA3** [Janpot/microdata-node#5]
Thank you for creating this module! It's almost perfect for my needs with one problem:  if an element contains two (or more) paragraph elements, the textContent from the second paragraph collides with the textContent from the first.  For example, given the input:
```
<div itemprop="description">
<p>Paragraph one</p>
<p>Paragraph two</p>
</div>
```
The value of "description" will be:

`Paragraph oneParagraph two`

When it should be more like:

`Paragraph one Paragraph two`

Could you please add handling for this case?

**Comment by Janpot** [comment]
[According to spec](https://www.w3.org/TR/microdata/#values), the value should be the node's [`textContent`](https://www.w3.org/TR/microdata/#values). Take note that this is different from the `innerText`.

Just a reminder that the `textContent` of 

```html
<div itemprop="description">
<p>Paragraph one</p>
<p>Paragraph two</p>
</div>
```

is `"\nParagraph one\nParagraph two\n"`
And the one of 

```html
<div itemprop="description"><p>Paragraph one</p><p>Paragraph two</p></div>
```

is `"Paragraph oneParagraph two"`.

If you still think this module works the wrong way, would you mind providing a test case in the form of a PR?

**Comment by AMA3** [comment]
Thanks for the quick response and thanks again for sharing this package with us. :)  If the module is acting according to spec then I'll accept it.

In case others have an issue with this behavior:  as an alternative solution for my use case, I decided to insert a space before every HTML opening tag before passing the HTML string to the .toJson() (I already have code in place to .trim() all of the values in the JSON object before using them).  For example:
```
let json = require('microdata-node').toJson(htmlSource.replace(/(<\w)/g,' $1'));
console.log( json.description.trim() );
```
